FILE_TMPDIR = "TMPDIR"

CONFIG_ENDPOINT_AFFERENCE = "AFFERENCE"
CONFIG_VERTEBRANAME = "NAME"
CONFIG_VERTEBRAID = "ID"
CONFIG_TASKNAME = "TASK_NAME"

SERVICE_PORT = "PORT"

MCR_PATH = "/opt/mcr/v98"

PMR_TASK_NAME = "PMR"
ACM_TASK_NAME = "ACM"
MR_TASK_NAME = "MR"
DI_TASK_NAME = "DI"

FILE_UPLOAD_PATH_TO_BLUEHOST = "apps/MROPTIMUM/mroQ/serviceAPI.php"
BLUEHOST_FALL2020_BASE_URL = "http://cloudmrhub.com/"

SERVER = BLUEHOST_FALL2020_BASE_URL
cloudmrhubQuerypath = SERVER + "Q"
cmServiceAPI = cloudmrhubQuerypath + "/serviceAPI.php"

OUTPUT_KEY = "output"