FILE_TMPDIR = "TMPDIR"

CONFIG_ENDPOINT_AFFERENCE = "AFFERENCE"
CONFIG_VERTEBRANAME = "NAME"
CONFIG_VERTEBRAID = "ID"
CONFIG_TASKNAME = "TASK_NAME"

SERVICE_PORT = "PORT"

MCR_PATH = "/opt/mcr/v98"

PMR_TASK_NAME = "PMR"
ACM_TASK_NAME = "ACM"
MR_TASK_NAME = "MR"
DI_TASK_NAME = "DI"

taskNames = [ACM_TASK_NAME, PMR_TASK_NAME, DI_TASK_NAME, MR_TASK_NAME]